### ISSUE TITLE
FastAPI - Python 3.7 - Nginx - Angular - MariaDB - Docker

### ISSUE THREAD

**Issue by bryanray67** [tiangolo/full-stack#23]
Hello, I recently stumbled upon your repositories and looked over the awesome work you have done.  It is truly amazing what you can accomplish so quickly with Docker.

I was originally looking to set up a Docker environment with Flask-Nginx-Angular, but after looking at your amazing FastAPI project, I'm leaning in that direction.
Do you plan on creating a Docker setup with FastAPI-Python 3.7-Nginx-MariaDB-Angular? 

Thanks for your amazing work!
Bryan

**Comment by tiangolo** [comment]
I'm glad it's been useful!

Yes, that's the next thing I'll do, an equivalent to this project but based on FastAPI. I hope to release it in the next days / week.

As everything is very modular, you can add your Angular code to replace the Vue.js frontend but keeping the Docker multi-stage build (if you want more details on Docker multi-stage build for Angular, check: https://medium.com/@tiangolo/angular-in-docker-with-nginx-supporting-environments-built-with-multi-stage-docker-builds-bb9f1724e984).

As the backend uses SQLAlchemy, you will be able to replace the PostgreSQL with MariaDB (or MySQL) very easily, mainly changing the Docker DB image.

About Nginx, as FastAPI is asynchronous, using Uvicorn with ASGI (instead of WSGI), is production ready, you don't need Nginx. Actually, it has some of the best achievable performances: https://fastapi.tiangolo.com/#performance

And if you use FastAPI you can use the official image: https://github.com/tiangolo/uvicorn-gunicorn-fastapi-docker

**Comment by bryanray67** [comment]
Hello Sebastián.
Thank you for your reply.  I see your comment about Nginx is not needed if I'm using FastAPI and Uvicorn.  This is my misunderstanding.  I thought Nginx would be needed to serve static files (html/css etc...) and FastAPI was only for the api.  I will read up on how to serve my Angular static files with Uvicorn.
Regards,
Bryan

**Comment by tiangolo** [comment]
Ah, get it. Actually, Nginx makes sense for your static files (and frontend). This stack (and the next one) have Nginx serving the frontend. But only that service. The backend is served by Uvicorn managed by Gunicorn.

**Comment by tiangolo** [comment]
Here it is! :tada: :cake: :rocket: 

FastAPI with PostgreSQL using SQLAlchemy: https://github.com/tiangolo/full-stack-fastapi-postgresql

You can change it to MariaDB or MySQL by modifying a couple of lines in the docker-compose files and a couple of lines in the code and the Alembic configs. But as it uses SQLAlchemy, most of the code should be quite standard for any of these relational DBs.

**Comment by tiangolo** [comment]
Hi @bryanray67 , I'll assume you were able to solve your problem and I'll close this issue now.

---

If you are still using this project, I suggest you check the equivalent [project generator for **FastAPI**](https://github.com/tiangolo/full-stack-fastapi-postgresql) that solves the same use cases in a much better way.

Because of that, this Flask-based project generator is [now going to be deprecated](https://github.com/tiangolo/full-stack#%EF%B8%8F-deprecation-warning-%EF%B8%8F). You are still free to use it, but it won't receive any new features, changes, or bug fixes.

**Comment by Nsandomeno** [comment]
@bryanray67 @tiangolo https://github.com/tiangolo/full-stack/issues/23#issuecomment-468948276

I'm having a lot of trouble fixing the Alembic config for this, any chance you can give me an idea for that?

I've done the docker-compose, alembic/env.py, app/core/config.py, as well as added the drivers as dependencies in pyproject.toml prior to building the image (from a clean spot as well).
