### ISSUE TITLE
Traefik on Swarm deploy

### ISSUE THREAD

**Issue by thewhipster** [tiangolo/full-stack#25]
I've successfully done a swarm deploy and found it curious that while traefik gets pushed out as a proxy image in the deploy, I couldn't reach the app until i added another Traefik stack following the dockerrocks process. (which is great btw). Is that redundant, or does the app use the proxy to internally route to the public Traefik stack?

**Comment by tiangolo** [comment]
Cool!

---

There are two Traefik instances. One global, for the whole Docker Swarm cluster that handles all the HTTPS. And one local for the stack, that redirects the communication to the backend or frontend, depending on the path.

**Comment by tiangolo** [comment]
Thanks! The problem with expect is that it won't start until those replicas are ready. And if you lost an entire node, Consul might not start at all.

There are a couple of issues in Traefik related to Consul. It seems it is not being able to generate new certificates after some time because it's not being able to acquire the lock. For the time being, I suggest using a single Traefik instance while that is fixed (I have to update that in the docs).

**Comment by tiangolo** [comment]
Hi @thewhipster , I'll assume you were able to solve your problem and I'll close this issue now.

---

If you are still using this project, I suggest you check the equivalent [project generator for **FastAPI**](https://github.com/tiangolo/full-stack-fastapi-postgresql) that solves the same use cases in a much better way.

Because of that, this Flask-based project generator is [now going to be deprecated](https://github.com/tiangolo/full-stack#%EF%B8%8F-deprecation-warning-%EF%B8%8F). You are still free to use it, but it won't receive any new features, changes, or bug fixes.
